#!/bin/bash
#Usage###########################################################
# $decontainerize <project>
# This stops the container and destroys wihtout taking any backup
# Use at high risk
#################################################################

project=$1

#First stop the container 

lxc-stop -n $project

#Wait for 10 seconds for safe stop

sleep 10

#Destroy the container

lxc-destroy -n $project

